# Generated by Django 5.1.1 on 2024-09-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasservicios',
            old_name='serivioid',
            new_name='serviciod',
        ),
    ]
